### ISSUE TITLE
Add unit tests to verify-conformance bot

### ISSUE THREAD

**Issue by Riaankl** [kubernetes-purgatory/apisnoop#736]
There are no tests associated with the verify-conformance bot and there is currently only smoke testing in the _cncf-infra/k8s-conformance_ repo with mock data.

With the usage of godog, fake clients and test data, unit tests should be written.

**Comment by BobyMCbobs** [comment]
unit test coverage is now at
- ok  	cncf.io/infra/verify-conformance-release/pkg/common	0.002s	coverage: 100.0% of statements
- ok  	cncf.io/infra/verify-conformance-release/pkg/plugin	0.062s	coverage: 13.4% of statements
- ok  	cncf.io/infra/verify-conformance-release/pkg/suite	0.841s	coverage: 63.8% of statements

**Comment by BobyMCbobs** [comment]
current unit test coverage is at
- ok  	cncf.io/infra/verify-conformance-release/pkg/common	0.286s	coverage: 100.0% of statements
- ok  	cncf.io/infra/verify-conformance-release/pkg/plugin	0.808s	coverage: 63.9% of statements
- ok  	cncf.io/infra/verify-conformance-release/pkg/suite	1.216s	coverage: 99.3% of statements

plugin is a tricky one to test and there's still a few functions which should be covered, such as `handle`

**Comment by BobyMCbobs** [comment]
thanks to https://github.com/cncf-infra/verify-conformance/pull/123, pkg/plugin coverage now at 79.7%
